stages:
  - build
  - publish

default:
  tags:
    - benzaiten-autoscale

# Global variable (can configure outside in gitlab web)
variables:
  ARTIFACT_DIR: "fdw_rpm"
  PGSPIDER_RELEASE_VERSION: "4.0.0-1"
  PGSPIDER_BASE_POSTGRESQL_VERSION: "16"
  PARQUET_S3_FDW_RELEASE_VERSION: "1.1.0"
  PGSPIDER_RPM_ID: "14997"
  AWS_S3_CPP_VERSION: "1.11.91"
  ARROW_VERSION: "12.0.0"
  PACKAGE_RELEASE_VERSION: "1"

project_build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    IMAGE_TAG: "fdw_build"
    DOCKERFILE: "Dockerfile_rpm"
  before_script:
    - export http_proxy=$PROXY && export https_proxy=$PROXY
    - export no_proxy=$NO_PROXY
    - apk add git && apk add wget
    # handle if the previous pipeline error
    - docker rm $(docker stop test) || true
    - docker rmi $IMAGE_TAG || true
    - echo "y" | docker system prune
    - echo "y" | docker volume prune
  script:
    # Get AWS-SDK-CPP and ARROW
    - cd rpm/deps/aws_s3_cpp && chmod -R 777 ./
    - git clone --depth 1 --recursive --branch $AWS_S3_CPP_VERSION https://github.com/aws/aws-sdk-cpp.git aws-sdk-cpp-$AWS_S3_CPP_VERSION > /dev/null
    - tar -czvf aws-sdk-cpp.tar.bz2 aws-sdk-cpp-$AWS_S3_CPP_VERSION > /dev/null
    - cd ../arrow && chmod -R 777 ./
    - wget https://github.com/apache/arrow/archive/refs/tags/apache-arrow-$ARROW_VERSION.tar.gz --no-check-certificate 
    - cd ../../..
    # Build
    - echo "Building RPM ....."
    - if [ $PGSPIDER_RPM_ID ]; then PGSPIDER_RPM_ID_POSTFIX="-$PGSPIDER_RPM_ID"; fi
    - docker build -t $IMAGE_TAG
                  --build-arg proxy=$PROXY
                  --build-arg no_proxy=$NO_PROXY
                  --build-arg ACCESS_TOKEN=$ACCESS_TOKEN
                  --build-arg PACKAGE_RELEASE_VERSION=$PACKAGE_RELEASE_VERSION
                  --build-arg PGSPIDER_BASE_POSTGRESQL_VERSION=$PGSPIDER_BASE_POSTGRESQL_VERSION
                  --build-arg PGSPIDER_RELEASE_VERSION=$PGSPIDER_RELEASE_VERSION
                  --build-arg PGSPIDER_RPM_ID=$PGSPIDER_RPM_ID_POSTFIX
                  --build-arg PGSPIDER_RPM_URL="$CI_API_V4_URL/projects/$PGSPIDER_PROJECT_ID/packages/generic/rpm_rhel8/$PGSPIDER_BASE_POSTGRESQL_VERSION"
                  --build-arg PARQUET_S3_FDW_RELEASE_VERSION=$PARQUET_S3_FDW_RELEASE_VERSION
                  --build-arg AWS_S3_CPP_VERSION=$AWS_S3_CPP_VERSION
                  --build-arg ARROW_VERSION=$ARROW_VERSION
                  -f rpm/$DOCKERFILE .
    # get rpm file from docker image
    - mkdir -p $ARTIFACT_DIR
    - docker run -d --name test $IMAGE_TAG /usr/sbin/init
    - docker cp test:/home/user1/rpmbuild/RPMS/x86_64 $ARTIFACT_DIR
    # clean-up: delete docker image
    - docker rm $(docker stop test)
    - docker rmi $IMAGE_TAG
    - cp $ARTIFACT_DIR/x86_64/* $ARTIFACT_DIR
    - rm -rf $ARTIFACT_DIR/x86_64/
  timeout: 3 hours
  artifacts:
    paths:
      - $ARTIFACT_DIR
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

# Push RPM to Registry job
project_publish:
  stage: publish
  before_script:
    - export http_proxy=$PROXY && export https_proxy=$PROXY
    - export no_proxy=$NO_PROXY
    - apt-get update -qq && apt-get install -y -qq curl
  variables:
    curl_command: "curl --header \"PRIVATE-TOKEN: $ACCESS_TOKEN\" --insecure --upload-file"
    package_uri: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/rpm_rhel8/$PGSPIDER_BASE_POSTGRESQL_VERSION"
  script:
    - echo "Publishing ....."
    # aws_s3_cpp
    - eval "$curl_command $ARTIFACT_DIR/arrow-$ARROW_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64.rpm
                          $package_uri/arrow-$ARROW_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64-$CI_PIPELINE_ID.rpm"
    # arrow
    - eval "$curl_command $ARTIFACT_DIR/aws_s3_cpp-$AWS_S3_CPP_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64.rpm
                          $package_uri/aws_s3_cpp-$AWS_S3_CPP_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64-$CI_PIPELINE_ID.rpm"
    # parquet_s3_fdw
    - eval "$curl_command $ARTIFACT_DIR/parquet_s3_fdw_$PGSPIDER_BASE_POSTGRESQL_VERSION-$PARQUET_S3_FDW_RELEASE_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64.rpm
                          $package_uri/parquet_s3_fdw_$PGSPIDER_BASE_POSTGRESQL_VERSION-$PARQUET_S3_FDW_RELEASE_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64-$CI_PIPELINE_ID.rpm"
    # debugsource
    - eval "$curl_command $ARTIFACT_DIR/parquet_s3_fdw_$PGSPIDER_BASE_POSTGRESQL_VERSION-debugsource-$PARQUET_S3_FDW_RELEASE_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64.rpm
                          $package_uri/parquet_s3_fdw_$PGSPIDER_BASE_POSTGRESQL_VERSION-debugsource-$PARQUET_S3_FDW_RELEASE_VERSION-$PACKAGE_RELEASE_VERSION.rhel8.x86_64-$CI_PIPELINE_ID.rpm"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
